### PR TITLE
Added support of table as hidden state of RNN. 

### PR DESCRIPTION
**Pull request by urikz**
##### Summary:
Hi, Clement!
Thank you for awesome Recurrent module. It helped me really a lot during my experiments!
However, I needed to use table as hidden state in RNN and even if [README](https://github.com/clementfarabet/lua---nnx/blob/master/README.md#nnx.Recurrent) states it's possible it didn't quite work for me.
Please, find a unit test `nnxtest.Recurrent_TestTable` in my pull requests which demonstrates it.
So I tried to fix the issue and at least the unit test runs successfully. I'm not lua/torch expert so let me know if I'm doing something wrong, so I can re-write it.

##### Test plan:
`$ luarocks make && th -lnnx -e "nnx.test{'Recurrent'}" && th -lnnx -e "nnx.test{'Recurrent_TestTable'}"`

### CODE REVIEW

**Comment by soumith** [comment]
The module is all thanks to @nicholas-leonard

**Comment by urikz** [comment]
sorry, my bad! @nicholas-leonard, please, take a look, when you will have time. Thanks in advance!

**Comment by nicholas-leonard** [comment]
I am looking into it. It should be merged by the end of the week.

**Comment by nicholas-leonard** [comment]
Ok. Made some related fixes. Running an experiment to see if it still converges. If all goes well, should merge tomorrow morning or tonight.

**Comment by urikz** [comment]
Thanks, @nicholas-leonard!

**Comment by nicholas-leonard** [comment]
Thanks @urikz.

**Pull request merged**
