### PR TITLE
Fix SoftMaxTree:sharedClone

### PR DESCRIPTION
**Pull request by akhti**
See https://github.com/clementfarabet/lua---nnx/issues/3

### CODE REVIEW

**Comment by nicholas-leonard** [comment]
Also, can you add 
```lua
smt.updates = self.updates
```
to [sharedClone](https://github.com/akhti/lua---nnx/blob/master/SoftMaxTree.lua#L327)
and change zeroGradParameters so that it uses 

```lua
for k,v in pairs(self.updates) do
  self.updates[k] = nil
end
```
Instead of `self.udpates = {}`. 

Also if you use this, make sure to call `updateParameters` on only one of the clones (or the original), or the same update will be performed multiple times.

**Comment by akhti** [comment]
Sure, thanks!

**Comment by akhti** [comment]
I there anything left to do?

**Comment by nicholas-leonard** [comment]
Thanks @akhti !

**Pull request merged**
